---
name: Build container image

"on":
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
  push:
    paths:
      - .github/workflows/build-container-image.yml
      - Containerfile
      - files/**
      - scripts/*
  pull_request:
    paths:
      - .github/workflows/build-container-image.yml
      - Containerfile
      - files/**
      - scripts/*

jobs:
  build-container-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        openstack_version:
          - victoria
          - wallaby
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup docker
        uses: docker/setup-buildx-action@v1

      - name: Login to container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: github.ref == 'refs/heads/main'

      - name: Build container image
        run: scripts/build.sh
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          VERSION: ${{ matrix.openstack_version }}
          REPOSITORY: osism/openstack-configuration-validator

      - name: Push container image
        run: |
          scripts/push.sh
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          VERSION: ${{ matrix.openstack_version }}
          REPOSITORY: osism/openstack-configuration-validator
        if: |
          github.repository == 'osism/openstack-configuration-validator' &&
          github.ref == 'refs/heads/main'
